import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

interface LanguageContextType {
  currentLanguage: string;
  availableLanguages: string[];
  changeLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Basic translation dictionary
const translations: Record<string, Record<string, string>> = {
  en: {
    // English translations
    'welcome': 'Welcome',
    'login': 'Login',
    'logout': 'Logout',
    'dashboard': 'Dashboard',
    'modules': 'Modules',
    'profile': 'Profile',
    'settings': 'Settings',
    'language': 'Language',
    'english': 'English',
    'urdu': 'Urdu',
    'select_language': 'Select Language',
    'personalized_learning': 'Personalized Learning',
    'chapter_progress': 'Chapter Progress',
    'complete': 'Complete',
    'incomplete': 'Incomplete',
    'continue_learning': 'Continue Learning',
    'start_learning': 'Start Learning',
    'save_preferences': 'Save Preferences',
    'learning_preferences': 'Learning Preferences',
    'experience_level': 'Experience Level',
    'beginner': 'Beginner',
    'intermediate': 'Intermediate',
    'advanced': 'Advanced',
    'learning_path': 'Learning Path',
    'self_paced': 'Self-Paced',
    'guided': 'Guided',
    'intensive': 'Intensive',
    'module_1_title': 'Module 1: The Robotic Nervous System (ROS 2)',
    'module_2_title': 'Module 2: The Digital Twin (Gazebo & Unity)',
    'module_3_title': 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
    'module_4_title': 'Module 4: Vision-Language-Action (VLA)',
    'capstone_project': 'Capstone Project',
    'autonomous_humanoid': 'Autonomous Humanoid Robot',
    'voice_control': 'Voice Control',
    'navigation': 'Navigation',
    'manipulation': 'Manipulation',
    'safety_behaviors': 'Safety & Fallback Behaviors',
    'progress_tracking': 'Progress Tracking',
    'analytics': 'Analytics',
    'personalized_recommendations': 'Personalized Recommendations',
    'email': 'Email',
    'password': 'Password',
    'sign_up': 'Sign Up',
    'sign_in': 'Sign In',
    'create_account': 'Create Account',
    'user_login': 'User Login',
    'account_created_successfully': 'Account created successfully!',
    'login_successful': 'Login successful!',
    'authentication_failed': 'Authentication failed. Please try again.',
    'already_logged_in': 'Already Logged In',
    'welcome_back': 'Welcome back',
    'already_have_account': 'Already have an account? ',
    'no_account': 'Don\'t have an account? ',
    'user_dashboard': 'User Dashboard',
    'user_profile': 'User Profile',
    'please_login_to_view_profile': 'Please login to view your profile',
    'user_info': 'User Information',
    'name': 'Name',
    'learning_preferences': 'Learning Preferences',
    'ai_assistant': 'AI Assistant',
    'ask_robotics_question': 'Ask a robotics question...',
    'send': 'Send',
    'complete': 'Complete',
    'interactive': 'Interactive',
    'robotics': 'Robotics',
    'education': 'Education',
    'from': 'From',
    'to': 'To',
    'with': 'With',
    'voice': 'Voice',
    'control': 'Control',
    'explore': 'Explore',
    'curriculum': 'Curriculum',
    'view': 'View',
    'all': 'All',
    'content': 'Content',
    'ros2': 'ROS2',
    'fundamentals': 'Fundamentals',
    'autonomous': 'Autonomous',
    'humanoid': 'Humanoid',
    'systems': 'Systems',
    'modules': 'Modules',
    'hands_on': 'Hands-on',
    'projects': 'Projects',
    'expert': 'Expert',
    'tutorials': 'Tutorials',
    'practical': 'Practical',
    'learning': 'Learning',
    'journey': 'Journey',
    'structured': 'Structured',
    'path': 'Path',
    'beginner': 'Beginner',
    'to': 'to',
    'expert': 'Expert',
    'foundation': 'Foundation',
    'learn': 'Learn',
    'architecture': 'Architecture',
    'and': 'And',
    'core': 'Core',
    'concepts': 'Concepts',
    'needed': 'Needed',
    'for': 'For',
    'simulation': 'Simulation',
    'master': 'Master',
    'environments': 'Environments',
    'testing': 'Testing',
    'development': 'Development',
    'ai': 'AI',
    'integration': 'Integration',
    'implement': 'Implement',
    'perception': 'Perception',
    'decision': 'Decision',
    'making': 'Making',
    'systems': 'Systems',
    'using': 'Using',
    'understand': 'Understand',
    'respond': 'Respond',
    'human': 'Human',
    'commands': 'Commands',
    'through': 'Through',
    'vision': 'Vision',
    'vla': 'VLA',
    'build': 'Build',
    'robots': 'Robots',
    'that': 'That',
    'voice': 'Voice',
    'what': 'What',
    'our': 'Our',
    'learners': 'Learners',
    'say': 'Say',
    'join': 'Join',
    'thousands': 'Thousands',
    'of': 'Of',
    'enthusiasts': 'Enthusiasts',
    'mastering': 'Mastering',
    'humanoid': 'Humanoid',
    'systems': 'Systems',
    'this': 'This',
    'course': 'Course',
    'transformed': 'Transformed',
    'my': 'My',
    'understanding': 'Understanding',
    'the': 'The',
    'hands': 'Hands',
    'on': 'On',
    'approach': 'Approach',
    'with': 'With',
    'real': 'Real',
    'code': 'Code',
    'examples': 'Examples',
    'made': 'Made',
    'complex': 'Complex',
    'concepts': 'Concepts',
    'accessible': 'Accessible',
    'engineer': 'Engineer',
    'vlasystems': 'VLA Systems',
    'module': 'Module',
    'was': 'Was',
    'particularly': 'Particularly',
    'impressive': 'Impressive',
    'i': 'I',
    'built': 'Built',
    'a': 'A',
    'robot': 'Robot',
    'which': 'Which',
    'responds': 'Responds',
    'to': 'To',
    'in': 'In',
    'just': 'Just',
    'two': 'Two',
    'weeks': 'Weeks',
    'researcher': 'Researcher',
    'capstone': 'Capstone',
    'project': 'Project',
    'gave': 'Gave',
    'me': 'Me',
    'the': 'The',
    'portfolio': 'Portfolio',
    'pieces': 'Pieces',
    'i': 'I',
    'needed': 'Needed',
    'land': 'Land',
    'dream': 'Dream',
    'job': 'Job',
    'at': 'At',
    'startup': 'Startup',
    'specialist': 'Specialist',
    'comprehensive': 'Comprehensive',
    'progress': 'Progress',
    'from': 'From',
    'middleware': 'Middleware',
    'to': 'To',
    'brain': 'Brain',
    'ready': 'Ready',
    'instructions': 'Instructions',
    'step': 'Step',
    'by': 'By',
    'step': 'Step',
    'pipelines': 'Pipelines',
    'with': 'With',
    'ready': 'Ready',
    'to': 'To',
    'use': 'Use',
    'examples': 'Examples',
    'for': 'For',
    'gazebo': 'Gazebo',
    'isaac': 'Isaac',
    'whisper': 'Whisper',
    'and': 'And',
    'gpt': 'GPT',
    'based': 'Based',
    'planners': 'Planners',
    'execute': 'Execute',
    'commands': 'Commands',
    'performs': 'Performs',
    'navigation': 'Navigation',
    'manipulates': 'Manipulates',
    'objects': 'Objects',
    'in': 'In',
    'realistic': 'Realistic',
    'environments': 'Environments',
    'advanced': 'Advanced',
    'technology': 'Technology',
    'stack': 'Stack',
    'simulation': 'Simulation',
    'first': 'First',
    'approach': 'Approach',
    'industry': 'Industry',
    'standard': 'Standard',
    'tools': 'Tools',
    'middleware': 'Middleware',
    'for': 'For',
    'control': 'Control',
    'nodes': 'Nodes',
    'topics': 'Topics',
    'services': 'Services',
    'actions': 'Actions',
    'perception': 'Perception',
    'slam': 'SLAM',
    'behavior': 'Behavior',
    'systems': 'Systems',
    'physics': 'Physics',
    'sensors': 'Sensors',
    'integration': 'Integration',
    'vision': 'Vision',
    'language': 'Language',
    'action': 'Action',
    'voice': 'Voice',
    'llm': 'LLM',
    'course': 'Course',
    'curriculum': 'Curriculum',
    'structured': 'Structured',
    'learning': 'Learning',
    'path': 'Path',
    'from': 'From',
    'fundamentals': 'Fundamentals',
    'to': 'To',
    'advanced': 'Advanced',
    'concepts': 'Concepts',
    'with': 'With',
    'hands': 'Hands',
    'on': 'On',
    'projects': 'Projects',
    'robotic': 'Robotic',
    'applications': 'Applications',
    'using': 'Using',
    'tools': 'Tools',
    'digital': 'Digital',
    'twin': 'Twin',
    'gazebo': 'Gazebo',
    '&': '&',
    'unity': 'Unity',
    'develop': 'Develop',
    'in': 'In',
    'realistic': 'Realistic',
    'environments': 'Environments',
    'physics': 'Physics',
    'simulation': 'Simulation',
    'sensor': 'Sensor',
    'modeling': 'Modeling',
    'and': 'And',
    'virtual': 'Virtual',
    'testing': 'Testing',
    'ai': 'AI',
    'brain': 'Brain',
    'nvidia': 'NVIDIA',
    'isaac': 'Isaac',
    'implement': 'Implement',
    'systems': 'Systems',
    'navigation': 'Navigation',
    'and': 'And',
    'intelligence': 'Intelligence',
    'robot': 'Robot',
    'decision': 'Decision',
    'making': 'Making',
    'vision': 'Vision',
    'language': 'Language',
    'action': 'Action',
    'vla': 'VLA',
    'integrate': 'Integrate',
    'and': 'And',
    'respond': 'Respond',
    'to': 'To',
    'human': 'Human',
    'complete': 'Complete',
    'integration': 'Integration',
    'bring': 'Bring',
    'all': 'All',
    'systems': 'Systems',
    'together': 'Together',
    'autonomous': 'Autonomous',
    'voice': 'Voice',
    'command': 'Command',
    'processing': 'Processing',
    'and': 'And',
    'natural': 'Natural',
    'language': 'Language',
    'understanding': 'Understanding',
    'environmental': 'Environmental',
    'spatial': 'Spatial',
    'reasoning': 'Reasoning',
    'safe': 'Safe',
    'operation': 'Operation',
    'with': 'With',
    'fallback': 'Fallback',
    'behaviors': 'Behaviors',
    'system': 'System',
    'integration': 'Integration',
    'and': 'And',
    'deployment': 'Deployment',
    'working': 'Working',
    'project': 'Project',
    'with': 'With',
    'environment': 'Environment',
    'architecture': 'Architecture',
    'diagram': 'Diagram',
    'and': 'And',
    'demo': 'Demo',
    'video': 'Video',
    'deliverables': 'Deliverables',
    'browse': 'Browse',
    'all': 'All',
    'chapters': 'Chapters',
    '&': '&',
    'content': 'Content',
    'capstone': 'Capstone',
    'project': 'Project',
    'integrate': 'Integrate',
    'everything': 'Everything',
    'you': 'You',
    've': 'Ve',
    'learned': 'Learned',
    'into': 'Into',
    'a': 'A',
    'complete': 'Complete',
    'humanoid': 'Humanoid',
    'system': 'System',
    'integrated': 'Integrated',
    'everything': 'Everything',
    'learned': 'Learned',
    'complete': 'Complete',
    'system': 'System',
    'integration': 'Integration',
    'active': 'Active',
    'forums': 'Forums',
    'connect': 'Connect',
    'with': 'With',
    'fellow': 'Fellow',
    'learners': 'Learners',
    'and': 'And',
    'experts': 'Experts',
    'to': 'To',
    'discuss': 'Discuss',
    'challenges': 'Challenges',
    'and': 'And',
    'solutions': 'Solutions',
    'in': 'In',
    'humanoid': 'Humanoid',
    'robotics': 'Robotics',
    'expert': 'Expert',
    'mentorship': 'Mentorship',
    'get': 'Get',
    'guidance': 'Guidance',
    'from': 'From',
    'industry': 'Industry',
    'professionals': 'Professionals',
    'with': 'With',
    'years': 'Years',
    'of': 'Of',
    'experience': 'Experience',
    'in': 'In',
    'robotics': 'Robotics',
    'development': 'Development',
    'project': 'Project',
    'showcase': 'Showcase',
    'share': 'Share',
    'your': 'Your',
    'creations': 'Creations',
    'and': 'And',
    'learn': 'Learn',
    'from': 'From',
    'others': 'Others',
    'innovative': 'Innovative',
    'implementations': 'Implementations',
    'advanced': 'Advanced',
    'analytics': 'Analytics',
    'track': 'Track',
    'your': 'Your',
    'with': 'With',
    'detailed': 'Detailed',
    'and': 'And',
    'receive': 'Receive',
    'personalized': 'Personalized',
    'learning': 'Learning',
    'path': 'Path',
    'recommendations': 'Recommendations',
    'based': 'Based',
    'on': 'On',
    'your': 'Your',
    'performance': 'Performance',
    'localization': 'Localization',
    'content': 'Content',
    'available': 'Available',
    'in': 'In',
    'multiple': 'Multiple',
    'languages': 'Languages',
    'including': 'Including',
    'urdu': 'Urdu',
    'to': 'To',
    'enable': 'Enable',
    'international': 'International',
    'accessibility': 'Accessibility',
    'and': 'And',
    'diverse': 'Diverse',
    'learning': 'Learning',
    'communities': 'Communities',
    'enterprise': 'Enterprise',
    'security': 'Security',
    'level': 'Level',
    'threat': 'Threat',
    'protection': 'Protection',
    'and': 'And',
    'comprehensive': 'Comprehensive',
    'data': 'Data',
    'privacy': 'Privacy',
    'measures': 'Measures',
    'for': 'For',
    'large': 'Large',
    'scale': 'Scale',
    'public': 'Public',
    'access': 'Access'
  },
  ur: {
    // Urdu translations
    'welcome': 'خوش آمدید',
    'login': 'لاگ ان کریں',
    'logout': 'لاگ آوٹ',
    'dashboard': 'ڈیش بورڈ',
    'modules': 'ماڈیولز',
    'profile': 'پروفائل',
    'settings': 'ترتیبات',
    'language': 'زبان',
    'english': 'انگریزی',
    'urdu': 'اردو',
    'select_language': 'زبان منتخب کریں',
    'personalized_learning': 'ذاتی نوعیت کی سیکھنے کی',
    'chapter_progress': 'چیپٹر کی پیشرفت',
    'complete': 'مکمل',
    'incomplete': 'نامکمل',
    'continue_learning': 'سیکھنا جاری رکھیں',
    'start_learning': 'سیکھنا شروع کریں',
    'save_preferences': 'ترجیحات محفوظ کریں',
    'learning_preferences': 'سیکھنے کی ترجیحات',
    'experience_level': 'تجربے کی سطح',
    'beginner': 'شروع کرنے والا',
    'intermediate': 'درمیانی',
    'advanced': 'اعلی درجے کا',
    'learning_path': 'سیکھنے کا راستہ',
    'self_paced': 'خود کی رفتار',
    'guided': 'راہ نما',
    'intensive': 'گہرا',
    'module_1_title': 'ماڈیول 1: روبوٹ کا نروس سسٹم (ROS 2)',
    'module_2_title': 'ماڈیول 2: ڈیجیٹل ٹوئن (گیزبو اور یونٹی)',
    'module_3_title': 'ماڈیول 3: AI روبوٹ براہین (NVIDIA Isaac)',
    'module_4_title': 'ماڈیول 4: ویژن-لینگویج-ایکشن (VLA)',
    'capstone_project': 'کیپ اسٹون پروجیکٹ',
    'autonomous_humanoid': 'خود مختار ہیومنوائڈ روبوٹ',
    'voice_control': 'صوتی کنٹرول',
    'navigation': 'نیویگیشن',
    'manipulation': 'مینوپولیشن',
    'safety_behaviors': 'حفاظت اور واپسی کے رویے',
    'progress_tracking': 'پیشرفت کا جائزہ',
    'analytics': 'تجزیات',
    'personalized_recommendations': 'ذاتی نوعیت کی سفارشات',
    'email': 'ای میل',
    'password': 'پاس ورڈ',
    'sign_up': 'سائن اپ کریں',
    'sign_in': 'سائن ان کریں',
    'create_account': 'اکاؤنٹ بنائیں',
    'user_login': 'صارف لاگ ان',
    'account_created_successfully': 'اکاؤنٹ کامیابی سے بن گیا!',
    'login_successful': 'لاگ ان کامیاب ہوا!',
    'authentication_failed': 'توثیق ناکام ہو گئی۔ براہ کرم دوبارہ کوشش کریں۔',
    'already_logged_in': 'پہلے سے لاگ ان ہیں',
    'welcome_back': 'واپس مبارک ہو',
    'already_have_account': 'پہلے سے اکاؤنٹ موجود ہے؟ ',
    'no_account': 'اکاؤنٹ نہیں ہے؟ ',
    'user_dashboard': 'صارف ڈیش بورڈ',
    'user_profile': 'صارف پروفائل',
    'please_login_to_view_profile': 'اپنا پروفائل دیکھنے کے لیے براہ کرم لاگ ان کریں',
    'user_info': 'صارف کی معلومات',
    'name': 'نام',
    'learning_preferences': 'سیکھنے کی ترجیحات',
    'ai_assistant': 'AI اسسٹنٹ',
    'ask_robotics_question': 'روبوٹس کے بارے میں سوال پوچھیں...',
    'send': 'بھیجیں',
    'complete': 'مکمل',
    'interactive': 'میں تفاعل',
    'robotics': 'روبوٹکس',
    'education': 'تعلیم',
    'from': 'سے',
    'to': 'کو',
    'with': 'کے ساتھ',
    'voice': 'صوت',
    'control': 'کنٹرول',
    'explore': 'دریافت کریں',
    'curriculum': 'نصاب',
    'view': 'دیکھیں',
    'all': 'تمام',
    'content': 'مواد',
    'ros2': 'ROS2',
    'fundamentals': 'بنیادیات',
    'autonomous': 'خودمختار',
    'humanoid': 'ہیومنوائڈ',
    'systems': 'سسٹم',
    'modules': 'ماڈیول',
    'hands_on': 'ہاتھوں سے',
    'projects': 'پروجیکٹس',
    'expert': 'ماہر',
    'tutorials': 'ٹیوٹوریلز',
    'practical': 'عملی',
    'learning': 'سیکھنا',
    'journey': 'سفر',
    'structured': 'منظم',
    'path': 'راستہ',
    'beginner': 'شروع کرنے والا',
    'to': 'کو',
    'expert': 'ماہر',
    'foundation': 'بنیاد',
    'learn': 'سیکھیں',
    'architecture': 'آرکیٹیکچر',
    'and': 'اور',
    'core': 'مرکزی',
    'concepts': 'تصورات',
    'needed': 'ضرورت ہے',
    'for': 'کے لیے',
    'simulation': 'سمولیشن',
    'master': 'ماہر',
    'environments': 'ماحول',
    'testing': 'ٹیسٹنگ',
    'development': 'تعمیر',
    'ai': 'AI',
    'integration': 'انضمام',
    'implement': 'نافذ کریں',
    'perception': 'ادراک',
    'decision': 'فیصلہ',
    'making': 'کرنا',
    'systems': 'سسٹم',
    'using': 'استعمال کرتے ہوئے',
    'understand': 'سمجھیں',
    'respond': 'جواب دیں',
    'human': 'انسان',
    'commands': 'حکم',
    'through': 'کے ذریعے',
    'vision': 'وژن',
    'vla': 'VLA',
    'build': 'تعمیر کریں',
    'robots': 'روبوٹس',
    'that': 'جو',
    'voice': 'صوت',
    'what': 'کیا',
    'our': 'ہمارا',
    'learners': 'سیکھنے والے',
    'say': 'کہتے ہیں',
    'join': 'شامل ہوں',
    'thousands': 'ہزاروں',
    'of': 'کے',
    'enthusiasts': 'شوقین',
    'mastering': 'ماہر بننا',
    'humanoid': 'ہیومنوائڈ',
    'systems': 'سسٹم',
    'this': 'یہ',
    'course': 'کورس',
    'transformed': 'تبدیل کر دیا',
    'my': 'میرا',
    'understanding': 'سمجھ',
    'the': 'کا',
    'hands': 'ہاتھ',
    'on': 'پر',
    'approach': 'انداز',
    'with': 'کے ساتھ',
    'real': 'حقیقی',
    'code': 'کوڈ',
    'examples': 'مثالیں',
    'made': 'بنایا',
    'complex': 'پیچیدہ',
    'concepts': 'تصورات',
    'accessible': 'قابل رسائی',
    'engineer': 'انجنیئر',
    'vlasystems': 'VLA سسٹم',
    'module': 'ماڈیول',
    'was': 'تھا',
    'particularly': 'خصوصاً',
    'impressive': 'قابل تحسین',
    'i': 'میں',
    'built': 'تعمیر کیا',
    'a': 'ایک',
    'robot': 'روبوٹ',
    'which': 'جس نے',
    'responds': 'جواب دیا',
    'to': 'کو',
    'in': 'میں',
    'just': 'صرف',
    'two': 'دو',
    'weeks': 'ہفتوں',
    'researcher': 'تحقیق کار',
    'capstone': 'کیپ اسٹون',
    'project': 'پروجیکٹ',
    'gave': 'دیا',
    'me': 'میرے',
    'the': 'کو',
    'portfolio': 'پورٹ فولیو',
    'pieces': 'ٹکڑے',
    'i': 'میں',
    'needed': 'چاہیے تھے',
    'land': 'حاصل کرنا',
    'dream': 'خواب',
    'job': 'نوکری',
    'at': 'میں',
    'startup': 'اسٹارٹ اپ',
    'specialist': 'ماہر',
    'comprehensive': 'جامع',
    'progress': 'پیشرفت',
    'from': 'سے',
    'middleware': 'مڈل ویئر',
    'to': 'تک',
    'brain': 'دماغ',
    'ready': 'تیار',
    'instructions': 'ہدایات',
    'step': 'قدم',
    'by': 'کے',
    'step': 'قدم',
    'pipelines': 'پائپ لائن',
    'with': 'کے ساتھ',
    'ready': 'تیار',
    'to': 'کے',
    'use': 'استعمال',
    'examples': 'مثالیں',
    'for': 'کے لیے',
    'gazebo': 'گیزبو',
    'isaac': 'آئی سیک',
    'whisper': 'ویسپر',
    'and': 'اور',
    'gpt': 'جی پی ٹی',
    'based': 'پر مبنی',
    'planners': 'منصوبہ ساز',
    'execute': 'انجام دیں',
    'commands': 'حکم',
    'performs': 'ادا کرتا ہے',
    'navigation': 'نیویگیشن',
    'manipulates': 'مینوپولیٹ کرتا ہے',
    'objects': 'اشیاء',
    'in': 'میں',
    'realistic': 'حقیقت پسندانہ',
    'environments': 'ماحول',
    'advanced': 'اعلی درجے کا',
    'technology': 'ٹیکنالوجی',
    'stack': 'اسٹیک',
    'simulation': 'سمولیشن',
    'first': 'پہلا',
    'approach': 'انداز',
    'industry': 'صنعت',
    'standard': 'معیار',
    'tools': 'اوزار',
    'middleware': 'مڈل ویئر',
    'for': 'کے لیے',
    'control': 'کنٹرول',
    'nodes': 'نودز',
    'topics': 'موضوعات',
    'services': 'خدمات',
    'actions': 'ایکشن',
    'perception': 'ادراک',
    'slam': 'SLAM',
    'behavior': 'رویہ',
    'systems': 'سسٹم',
    'physics': 'طبیعیات',
    'sensors': 'سینسرز',
    'integration': 'انضمام',
    'vision': 'وژن',
    'language': 'زبان',
    'action': 'ایکشن',
    'voice': 'صوت',
    'llm': 'LLM',
    'course': 'کورس',
    'curriculum': 'نصاب',
    'structured': 'منظم',
    'learning': 'سیکھنا',
    'path': 'راستہ',
    'from': 'سے',
    'fundamentals': 'بنیادیات',
    'to': 'تک',
    'advanced': 'اعلی درجے کا',
    'concepts': 'تصورات',
    'with': 'کے ساتھ',
    'hands': 'ہاتھ',
    'on': 'پر',
    'projects': 'پروجیکٹس',
    'robotic': 'روبوٹک',
    'applications': 'ایپلی کیشنز',
    'using': 'استعمال کرتے ہوئے',
    'tools': 'اوزار',
    'digital': 'ڈیجیٹل',
    'twin': 'جڑواں',
    'gazebo': 'گیزبو',
    '&': 'اور',
    'unity': 'یونٹی',
    'develop': 'ترقی دیں',
    'in': 'میں',
    'realistic': 'حقیقت پسندانہ',
    'environments': 'ماحول',
    'physics': 'طبیعیات',
    'simulation': 'سمولیشن',
    'sensor': 'سینسر',
    'modeling': 'ماڈلنگ',
    'and': 'اور',
    'virtual': 'مجازی',
    'testing': 'ٹیسٹنگ',
    'ai': 'AI',
    'brain': 'دماغ',
    'nvidia': 'این ویڈیا',
    'isaac': 'آئی سیک',
    'implement': 'نافذ کریں',
    'systems': 'سسٹم',
    'navigation': 'نیویگیشن',
    'and': 'اور',
    'intelligence': 'ذہانت',
    'robot': 'روبوٹ',
    'decision': 'فیصلہ',
    'making': 'کرنا',
    'vision': 'وژن',
    'language': 'زبان',
    'action': 'ایکشن',
    'vla': 'VLA',
    'integrate': 'انضمام',
    'and': 'اور',
    'respond': 'جواب دیں',
    'to': 'کو',
    'human': 'انسان',
    'complete': 'مکمل',
    'integration': 'مکمل انضمام',
    'bring': 'لائیں',
    'all': 'تمام',
    'systems': 'سسٹم',
    'together': 'ایک ساتھ',
    'autonomous': 'خودمختار',
    'voice': 'صوت',
    'command': 'حکم',
    'processing': 'پروسیسنگ',
    'and': 'اور',
    'natural': 'قدرتی',
    'language': 'زبان',
    'understanding': 'سمجھ',
    'environmental': 'ماحولیاتی',
    'spatial': 'جگہی',
    'reasoning': 'استدلال',
    'safe': 'محفوظ',
    'operation': 'کارروائی',
    'with': 'کے ساتھ',
    'fallback': 'واپسی',
    'behaviors': 'رویے',
    'system': 'سسٹم',
    'integration': 'انضمام',
    'and': 'اور',
    'deployment': 'تنصیب',
    'working': 'کام کر رہا',
    'project': 'پروجیکٹ',
    'with': 'کے ساتھ',
    'environment': 'ماحول',
    'architecture': 'آرکیٹیکچر',
    'diagram': 'ڈائیاگرام',
    'and': 'اور',
    'demo': 'ڈیمو',
    'video': 'ویڈیو',
    'deliverables': 'پہنچائے گئے',
    'browse': 'براؤز کریں',
    'all': 'تمام',
    'chapters': 'چیپٹر',
    '&': 'اور',
    'content': 'مواد',
    'capstone': 'کیپ اسٹون',
    'project': 'پروجیکٹ',
    'integrate': 'انضمام',
    'everything': 'سب کچھ',
    'you': 'آپ',
    've': 'ہیں',
    'learned': 'سیکھا',
    'into': 'میں',
    'a': 'ایک',
    'complete': 'مکمل',
    'humanoid': 'ہیومنوائڈ',
    'system': 'سسٹم',
    'integrated': 'انضمام',
    'everything': 'سب کچھ',
    'learned': 'سیکھا',
    'complete': 'مکمل',
    'system': 'سسٹم',
    'integration': 'انضمام',
    'active': 'فعال',
    'forums': 'فورمز',
    'connect': 'منسلک ہوں',
    'with': 'کے ساتھ',
    'fellow': 'ساتھی',
    'learners': 'سیکھنے والے',
    'and': 'اور',
    'experts': 'ماہرین',
    'to': 'کے لیے',
    'discuss': 'بحث کریں',
    'challenges': 'چیلنجز',
    'and': 'اور',
    'solutions': 'حل',
    'in': 'میں',
    'humanoid': 'ہیومنوائڈ',
    'robotics': 'روبوٹکس',
    'expert': 'ماہر',
    'mentorship': 'راہ نمائی',
    'get': 'حاصل کریں',
    'guidance': 'ہدایات',
    'from': 'سے',
    'industry': 'صنعت',
    'professionals': 'پیشہ ورانہ',
    'with': 'کے ساتھ',
    'years': 'سالوں',
    'of': 'کے',
    'experience': 'تجربہ',
    'in': 'میں',
    'robotics': 'روبوٹکس',
    'development': 'تعمیر',
    'project': 'پروجیکٹ',
    'showcase': 'ظاہر کریں',
    'share': 'شیئر کریں',
    'your': 'آپ کا',
    'creations': 'تخلیقات',
    'and': 'اور',
    'learn': 'سیکھیں',
    'from': 'سے',
    'others': 'دوسروں',
    'innovative': 'نوآورانہ',
    'implementations': 'نفاذ',
    'advanced': 'اعلی درجے کا',
    'analytics': 'تجزیات',
    'track': 'ٹریک کریں',
    'your': 'آپ کا',
    'with': 'کے ساتھ',
    'detailed': 'تفصیلی',
    'and': 'اور',
    'receive': 'وصول کریں',
    'personalized': 'ذاتی نوعیت کا',
    'learning': 'سیکھنا',
    'path': 'راستہ',
    'recommendations': 'سفارشات',
    'based': 'مبنی',
    'on': 'پر',
    'your': 'آپ کا',
    'performance': 'کارکردگی',
    'localization': 'مقامیکرن',
    'content': 'مواد',
    'available': 'دستیاب',
    'in': 'میں',
    'multiple': 'متعدد',
    'languages': 'زبانیں',
    'including': 'بشمول',
    'urdu': 'اردو',
    'to': 'کے لیے',
    'enable': 'قابل بنائیں',
    'international': 'بین الاقوامی',
    'accessibility': 'قابلیت',
    'and': 'اور',
    'diverse': 'متنوع',
    'learning': 'سیکھنا',
    'communities': 'کمیونٹیز',
    'enterprise': 'ادارہ',
    'security': 'سیکورٹی',
    'level': 'سطح',
    'threat': 'خطرہ',
    'protection': 'تحفظ',
    'and': 'اور',
    'comprehensive': 'جامع',
    'data': 'ڈیٹا',
    'privacy': 'رازداری',
    'measures': 'اجراء',
    'for': 'کے لیے',
    'large': 'بڑا',
    'scale': 'پیمانہ',
    'public': 'عوامی',
    'access': 'رسائی'
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<string>(() => {
    // Initialize with 'en' during SSR, then update after mount if needed
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('language');
      return savedLanguage || 'en';
    }
    return 'en'; // Default during SSR
  });

  useEffect(() => {
    // Update language after mount if different from SSR value
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('language');
      if (savedLanguage && savedLanguage !== currentLanguage) {
        setCurrentLanguage(savedLanguage);
      }
    }
  }, []); // Only run once after mount

  const availableLanguages = ['en', 'ur'];

  const changeLanguage = (lang: string) => {
    if (availableLanguages.includes(lang)) {
      setCurrentLanguage(lang);
      if (typeof window !== 'undefined') {
        localStorage.setItem('language', lang);
      }
    }
  };

  const t = (key: string): string => {
    // Return translation if available, otherwise return key
    return translations[currentLanguage]?.[key] || key;
  };

  const value = {
    currentLanguage,
    availableLanguages,
    changeLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    // During SSR or if context is not available, return a default value
    // This prevents the error while still providing basic functionality
    console.warn('useLanguage is being used outside of LanguageProvider - using default values');
    return {
      currentLanguage: 'en',
      availableLanguages: ['en', 'ur'],
      changeLanguage: () => {},
      t: (key: string) => key, // Return the key as-is if no context available
    };
  }
  return context;
};